Add function: Load Text from .txt file
youknowone/Say pull request #21
Opened 2016-09-24 11:10 UTC by pmw9027

Create toolbarItem : Import
Insert Function : Insert text from file

2016-09-24 11:20 UTC, youknowone commented
Let's update localization for this feature: http://stackoverflow.com/questions/15094259/is-it-possible-to-update-a-localized-storyboards-strings
The localization strings resource file is here: https://github.com/youknowone/Say/blob/master/Say/ko.lproj/Main.strings

2016-09-24 11:25 UTC, closer27 commented on Say/ViewController.swift
> +        catch {/* error handling here */}
How about adding some friendly popup, If `Say` get a unsuppored file.

2016-09-24 11:29 UTC, closer27 commented
I love this feature, but `Say` seems to need Error handling for an unsupported file.

2016-09-24 11:30 UTC, closer27 approved these changes
It looks great for `Say`

2016-09-24 11:58 UTC, youknowone commented on Say/ViewController.swift
> +    @IBOutlet var importToolbarItem: NSToolbarItem! = nil;
Apple prefer "Open" and "열기" for this kind of behavior

2016-09-24 11:58 UTC, youknowone commented
In menu bar, there also is "Open" bar. It must be connected to the open feature by Apple App Store review guideline.

2016-09-25 06:59 UTC, pmw9027 commented on Say/ViewController.swift
> +        catch {/* error handling here */}
Thanks you for your review

2016-09-25 06:59 UTC, pmw9027 commented on Say/ViewController.swift
> +    @IBOutlet var importToolbarItem: NSToolbarItem! = nil;
Thanks you for your review
I fixed it!

2016-09-25 08:54 UTC, youknowone commented on Say/ViewController.swift
> +    @IBOutlet var importToolbarItem: NSToolbarItem! = nil;
One more stuff: Swift doesn't require semicolon end of the statement. Will you remove it too? (It is fault of the original code)

2016-09-25 12:33 UTC, youknowone commented on Say/ko.lproj/Main.strings
> +"IAo-SY-fd9.title" = "열기";
`...` means it will open a model window to ask more informations. So it must be '열기...' rather than '열기'

2016-09-25 12:34 UTC, youknowone commented on Say/ko.lproj/Main.strings
> +"ZA3-HX-azw.label" = "불러오기";
This is not `Import` anymore so '열기' too

2016-09-25 12:34 UTC, youknowone commented on Say/en.lproj/Main.strings
> +
I don't think we need Main.strings for english

2016-09-25 12:36 UTC, youknowone requested changes
I requested 3 more changes. It seems that's all of changes we need. Thanks for nice work :D

2016-09-26 08:35 UTC, merged

2016-09-26 10:13 UTC, closer27 commented
I've used this feature, It's really useful, @pmw9027 you well done. 😆