iOS base UI and functions
youknowone/Say pull request #23
Opened 2016-09-24 12:12 UTC by Amanida

Added base UI : TextView for input text, 'Play' Button, 'Select Language Button. Title bar
Completed feature : Playing text with Korean voice
Now working : Adding action sheet with picker View. Selecting language feature.

2016-09-24 14:39 UTC, youknowone commented
I found the width of the alert view becomes shorter after presenting it.
Insert the following code:
```
        self.languagePicker.autoresizingMask = [UIViewAutoresizing.flexibleLeftMargin, UIViewAutoresizing.flexibleRightMargin]
```

2016-09-24 15:09 UTC, Amanida commented
Thank you for review. I applied your code and resizing picker view. Please check this tomorrow...not today! :)

2016-09-25 08:49 UTC, youknowone commented on iOS/Speaker.swift
> +    var voice = AVSpeechSynthesisVoice(language: "ko-KR")     // set default language : korean
Say shouldn't set korean as default language. We should guess system default language, but "en-US" will be ok for the first step.

2016-09-25 08:50 UTC, youknowone commented on iOS/Speaker.swift
> +        utterance.rate = 0.4
Default speech rate will be better.

2016-09-25 08:52 UTC, youknowone commented on iOS/ViewController.swift
> +        let alertView = UIAlertController(title: "Select Launguage", message: "\n\n\n\n\n\n\n\n\n\n", preferredStyle: UIAlertControllerStyle.actionSheet);
`alertController` instead of `alertView`

2016-09-25 08:52 UTC, youknowone commented on iOS/ViewController.swift
> +        languagePicker = UIPickerView(frame: CGRect(x: 0, y: 20, width: 300, height: 250))
I think the size must not be set as fixed, but flexible ralative to the alert view width.
for example:
width = alertView's width - 40

2016-09-25 08:53 UTC, youknowone requested changes

2016-09-26 09:14 UTC, merged