Pause function
youknowone/Say pull request #32
Opened 2016-09-26 08:00 UTC by pmw9027

insert pause toolbar item

2016-09-26 08:54 UTC, youknowone commented
Because loading text is merged in other PR, rebase will be appricated.

2016-09-26 16:13 UTC, youknowone commented
I found it - you should disable `autovalidate` property of the ToolbarItem in the storyboard.
Then it will allow you to change isEnabled manually.

2016-09-27 04:30 UTC, youknowone commented
Will you rebase the this PR?

2016-09-27 11:41 UTC, AWEEKJ commented on Say/ViewController.swift
> +    //@IBOutlet var statusMenu: NSMenu! = nil
Do we need to remain these comments? It looks unnecessary to remain these two lines ;(

2016-09-27 11:44 UTC, AWEEKJ commented on Say/ViewController.swift
> +    }
I think there is too many empty lines here. How about clean up these spaces?

2016-09-27 12:00 UTC, youknowone requested changes

2016-09-27 12:00 UTC, youknowone commented on Say/Say.swift
> +    var speechToolBar:NSToolbarItem? = nil
Is this used anywhere?

2016-09-27 12:00 UTC, youknowone commented on Say/Say.swift
> +
redundant whitespace

2016-09-27 12:00 UTC, youknowone commented on Say/Say.swift
> +    /*
meaningless comments

2016-09-27 12:00 UTC, youknowone commented on Say/ViewController.swift
> +        speechToolbarItem.autovalidates = false
You can change this value in Interface builder.

2016-09-27 12:00 UTC, youknowone commented on SayKit
> +Subproject commit 2054a7e6c36e8d00bc99ff6ce06c1fe833e098f3
SayKit shouln't revive.

2016-09-27 12:00 UTC, youknowone commented on Say/ViewController.swift
> +                //sender.isEnabled = false
let's sweep out non-using codes

2016-09-27 12:03 UTC, youknowone requested changes

2016-09-27 12:03 UTC, youknowone commented on Say/Say.swift
> +    func continueSpeeking(){
code style `() {`

2016-09-27 12:38 UTC, youknowone requested changes

2016-09-27 12:38 UTC, youknowone commented on Say/ViewController.swift
> +        if !say.isplaying(){
`() {`

2016-09-27 12:39 UTC, youknowone requested changes

2016-09-27 12:39 UTC, youknowone commented on Say/ViewController.swift
> +            }
we use `} else {` widely in this project

2016-09-27 12:39 UTC, youknowone commented on SayKit
> +Subproject commit 2054a7e6c36e8d00bc99ff6ce06c1fe833e098f3
You didn't remove SayKit yet.

2016-09-27 13:21 UTC, Amanida commented on Say/ViewController.swift
> +            }
say.continueSpeeking() -> say.continue**Speaking()** 😄

2016-09-27 13:22 UTC, youknowone commented on Say/ViewController.swift
> +            }
Nice catch. It looks a glitch of SayAPI

2016-09-27 13:25 UTC, pmw9027 commented on Say/ViewController.swift
> +            }
oops..I modified

2016-09-28 01:22 UTC, merged